# Generated by Django 4.1.7 on 2023-04-03 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код проекта')),
                ('project_name', models.CharField(help_text='Название проекта', max_length=50, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('userProject_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код проект-пользователь')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.projects', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект пользователя',
                'verbose_name_plural': 'Проекты пользователя',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('testCase_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код тест-кейса')),
                ('title', models.CharField(max_length=100, verbose_name='Названеи')),
                ('precondition', models.TextField(verbose_name='Предусловия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('expectedResult', models.TextField(verbose_name='Ожидаемый результат')),
                ('isAutomated', models.BooleanField(verbose_name='Автоматизирован')),
                ('caseCreated_date', models.DateTimeField(verbose_name='Создано')),
                ('caseLastModified_date', models.DateTimeField(verbose_name='Изменено')),
                ('caseCreated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('caseLastModified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Последние изменения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Тест-кейс',
                'verbose_name_plural': 'Тест-кейсы',
            },
        ),
    ]
