# Generated by Django 4.1.7 on 2023-04-03 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код проекта')),
                ('project_name', models.CharField(help_text='Название проекта', max_length=50, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='TestPriorities',
            fields=[
                ('testPriority_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код приоритета')),
                ('testPriority_name', models.CharField(max_length=50, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты',
            },
        ),
        migrations.CreateModel(
            name='TestStatuses',
            fields=[
                ('testStatus_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код статуса')),
                ('testStatus_name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус теста',
                'verbose_name_plural': 'Статусы тестов',
            },
        ),
        migrations.CreateModel(
            name='TestSuites',
            fields=[
                ('testSuite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код набора')),
                ('testSuite_name', models.CharField(max_length=50, verbose_name='Название набора')),
            ],
            options={
                'verbose_name': 'Тестовй набор',
                'verbose_name_plural': 'Тестовые наборы',
            },
        ),
        migrations.CreateModel(
            name='TestTypes',
            fields=[
                ('testType_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код типа')),
                ('testType_name', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип теса',
                'verbose_name_plural': 'Типы тестов',
            },
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('userProject_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код проект-пользователь')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.projects', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект пользователя',
                'verbose_name_plural': 'Проекты пользователя',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('testCase_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код тест-кейса')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('precondition', models.TextField(blank=True, null=True, verbose_name='Предусловия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('expectedResult', models.TextField(blank=True, null=True, verbose_name='Ожидаемый результат')),
                ('isAutomated', models.BooleanField(verbose_name='Автоматизирован')),
                ('caseCreated_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('caseLastModified_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('caseCreated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('caseLastModified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Последние изменения')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testpriorities', verbose_name='Приоритет')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.projects', verbose_name='Проект')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.teststatuses', verbose_name='Статус')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testsuites', verbose_name='Набор теста')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testtypes', verbose_name='Тип теста')),
            ],
            options={
                'verbose_name': 'Тест-кейс',
                'verbose_name_plural': 'Тест-кейсы',
            },
        ),
    ]
