# Generated by Django 4.1.7 on 2023-04-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtypes',
            options={'verbose_name': 'Тип теста', 'verbose_name_plural': 'Типы тестов'},
        ),
        migrations.AlterField(
            model_name='testcases',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='tests.teststatuses', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testsuites', verbose_name='Группа'),
        ),
    ]
