# Generated by Django 4.1.7 on 2023-04-03 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0003_teststeps_testcasesteps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlans',
            fields=[
                ('testPlan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код тест-плана')),
                ('title', models.CharField(max_length=50, verbose_name='Название тест-плана')),
                ('description', models.TextField(verbose_name='Описание тест-плана')),
            ],
            options={
                'verbose_name': 'Тест-план',
                'verbose_name_plural': 'Тест-планы',
            },
        ),
        migrations.CreateModel(
            name='TestCasePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimatedTime', models.PositiveIntegerField(verbose_name='Время')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testcases', verbose_name='Тест-кейс')),
                ('testCaseAssigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Назанчено')),
                ('testPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testplans', verbose_name='Тест план')),
            ],
            options={
                'verbose_name': 'TestCasePlans',
                'verbose_name_plural': 'TestCasePlanss',
            },
        ),
    ]
