# Generated by Django 4.1.7 on 2023-04-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_tags_testcaseresults_alter_testcaseplans_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseplans',
            name='testCaseResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.testcaseresults', verbose_name='Результат теста'),
        ),
    ]
