# Generated by Django 4.1.7 on 2023-04-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_testcaseplans_testcaseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuites',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tests.projects', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
