# Generated by Django 4.1.7 on 2023-05-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_projects_options_rename_project_id_projects_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.testsuites', verbose_name='Группа'),
        ),
    ]
