# Generated by Django 4.1.7 on 2023-05-09 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0014_alter_testcasetags_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseplans',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назанчено'),
        ),
        migrations.AlterField(
            model_name='testcaseplans',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testcases', verbose_name='Тест-кейс'),
        ),
        migrations.AlterField(
            model_name='testcaseplans',
            name='testPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testplans', verbose_name='Тест план'),
        ),
    ]
